(add-to-list 'load-path "~/Internet/Git/Emacs/emacs-w3m")
(add-to-list 'load-path "~/Internet/Git/Emacs/eacl")
(add-to-list 'load-path "~/Internet/Git/Emacs/deno-bridge")
(add-to-list 'load-path "~/Internet/Git/Emacs/emmet2-mode")
(add-to-list 'load-path "~/Internet/Git/Emacs/prettier.el/")
(add-to-list 'load-path "~/Internet/Git/Emacs/emacs-websocket/")
(add-to-list 'load-path "~/Internet/Git/Emacs/iter2/")
(add-to-list 'load-path "~/Internet/Git/Emacs/s.el/")
(add-to-list 'load-path "~/Internet/Git/Emacs/f.el/")
(add-to-list 'load-path "~/Internet/Git/Emacs/editorconfig-emacs/")
(add-to-list 'load-path "~/Internet/Git/Emacs/nvm.el/")
(add-to-list 'load-path "~/Internet/Git/Emacs/with-editor/lisp/")
(add-to-list 'load-path "~/Internet/Git/Emacs/dash.el/")
(add-to-list 'load-path "~/Internet/Git/Emacs/transient/")
(add-to-list 'load-path "~/Internet/Git/Emacs/magit/lisp/")
(add-to-list 'load-path "~/Internet/Git/Utility/emacs-pcre")

(load-file "~/Internet/Git/Utility/hop.el/hop.el")

(require 's)
(require 'f)
(require 'nvm)
(require 'editorconfig)
(require 'prettier)
(require 'eacl)
(require 'emmet2-mode)
(require 'mime-w3m)
(require 'w3m-load)
(require 'dash)
(require 'with-editor)
(require 'magit)

(defvar wymux-emacs-package-dir "~/Internet/Git/Emacs/")
(defvar wymux-bin-dir (concat user-emacs-directory "bin/"))
(defvar wymux-lib-dir (concat user-emacs-directory "lib/"))

(defun wymux/load-bin (file)
  "Load lib/'file'/'file'.el"
  (interactive)
  (load-file (concat wymux-bin-dir file "/" file ".el")))

(defun wymux/load-lib (file)
  "Load lib/'file'/'file'.el"
  (interactive)
  (load-file (concat wymux-lib-dir file "/" file ".el")))

(defun wymux/add-load-path (dir)
  ""
  (add-to-list 'load-path (concat wymux-emacs-package-dir dir)))

(wymux/load-bin "exwm")

(wymux/load-lib "abbrev")
(wymux/load-lib "backup")
(wymux/load-lib "compilation")
(wymux/load-lib "dired")
(wymux/load-lib "display")
(wymux/load-lib "eat")
(wymux/load-lib "emms")
(wymux/load-lib "eshell")
(wymux/load-lib "exwm")
(wymux/load-lib "ggtags")
(wymux/load-lib "gnus")
(wymux/load-lib "hotfuzz")
(wymux/load-lib "keybind")
(wymux/load-lib "mh")
(wymux/load-lib "misc")
(wymux/load-lib "mode")
(wymux/load-lib "prettier")
(wymux/load-lib "recentf")
(wymux/load-lib "register")
(wymux/load-lib "tree-sitter")
(wymux/load-lib "vertico")
